taama:
    resource: "@TaamaBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#hwioauthredirect:
#    resource: '@HWIOAuthBundle/Resources/config/routing/redirect.xml'
#    prefix: /connect

#hwioauthconnect:
#    resource: '@HWIOAuthBundle/Resources/config/routing/connect.xml'
#    prefix: /connect

#hwioauthlogin:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix: /login


#facebook_login:
#    path: /login/check-facebook

#google_login:
#    path: /login/check-google

#custom_login:
#    path: /login/check-custom

#github_login:
#    path: /login/check-github